openapi: 3.0.1
info:
  title: Sample API
  version: "1.0"
paths:
  /users:
    get:
      summary: List users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
components:
  schemas:
    UserList:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: string
          absoluteRef: "my-ref path of id"
          pointer: "#/components/schema/id"
        name:
          type: string
          absoluteRef: "my-ref path of name"
          pointer: "#/components/schema/name"